services:
  accounts:
    image: timmawv/accounts
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank

  loans:
    image: timmawv/loans
    container_name: loans-ms
    ports:
      - "8090:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank

  cards:
    image: timmawv/cards
    container_name: cards-ms
    ports:
      - "9000:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank

networks:
  bank:
    driver: "bridge"