spring:
  application:
    name: "accounts"
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  config:
    import: "optional:configserver:http://localhost:8071/" #если нет доступа то мы все равно включим микросервис

management:
  endpoints:
    web:
      exposure:
        include: "*" #это значит чтоб все возможные энд поинты были доступны

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

springdoc:
  swagger-ui:
    url: /swagger.yaml