services:
  configserver:
    image: timmawv/configserver
    container_name: configserver-ms
    ports:
      - "8071:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yaml
      service: microservice-base-config

  eurekaserver:
    image: timmawv/eurekaserver
    container_name: eurekaserver-ms
    ports:
      - "8070:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yaml
      service: microservice-configserver-config
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver" #это делаем из за бага

  accounts:
    image: timmawv/accounts
    container_name: accounts-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "accounts" #это делаем из за бага
    depends_on:
      eurekaserver:
        condition: service_healthy
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yaml
      service: microservice-eureka-config

  loans:
    image: timmawv/loans
    container_name: loans-ms
    ports:
      - "8090:8080"
    environment:
      SPRING_APPLICATION_NAME: "loans" #это делаем из за бага
    depends_on:
      eurekaserver:
        condition: service_healthy
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yaml
      service: microservice-eureka-config

  cards:
    image: timmawv/cards
    container_name: cards-ms
    ports:
      - "9000:8080"
    environment:
      SPRING_APPLICATION_NAME: "cards" #это делаем из за бага
    depends_on:
      eurekaserver:
        condition: service_healthy
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yaml
      service: microservice-eureka-config

networks:
  bank:
    driver: "bridge"