services:
  configserver:
    image: timmawv/configserver:${POM_VERSION}
    container_name: configserver-ms
    ports:
      - "8071:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yaml
      service: microservice-base-config

  gatewayserver:
    image: timmawv/gatewayserver:${POM_VERSION}
    container_name: gatewayserver-ms
    ports:
      - "8072:8080"
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver" #это делаем из за бага
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_TIMEOUT: 1s
      SPRING_DATA_REDIS_CONNECT_TIMEOUT: 2s
    depends_on:
      accounts:
        condition: service_healthy
      loans:
        condition: service_healthy
      cards:
        condition: service_healthy
      redis:
        condition: service_healthy
    extends:
      file: common-config.yaml
      service: microservice-eureka-config

  eurekaserver:
    image: timmawv/eurekaserver:${POM_VERSION}
    container_name: eurekaserver-ms
    ports:
      - "8070:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yaml
      service: microservice-configserver-config
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver" #это делаем из за бага

  accounts:
    image: timmawv/accounts:${POM_VERSION}
    container_name: accounts-ms
    ports:
      - "8080:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "accounts" #это делаем из за бага
    depends_on:
      eurekaserver:
        condition: service_healthy
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yaml
      service: microservice-eureka-config

  loans:
    image: timmawv/loans:${POM_VERSION}
    container_name: loans-ms
    ports:
      - "8090:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "loans" #это делаем из за бага
    depends_on:
      eurekaserver:
        condition: service_healthy
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yaml
      service: microservice-eureka-config

  cards:
    image: timmawv/cards:${POM_VERSION}
    container_name: cards-ms
    ports:
      - "9000:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "cards" #это делаем из за бага
    depends_on:
      eurekaserver:
        condition: service_healthy
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yaml
      service: microservice-eureka-config

  redis:
    container_name: redis-ms
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      timeout: 10s
      retries: 10
    extends:
      file: common-config.yaml
      service: network-deploy-service

networks:
  bank:
    driver: "bridge"