apiVersion: apps/v1 #зарезервированное имя
kind: Deployment #зарезервированное имя для типа запуска
metadata:
  name: configserver-deployment
  labels:
    app: configserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
        - name: configserver
          image: timmawv/configserver:0.0.12
          ports:
            - containerPort: 8080
--- #показывает что это 2 разных yaml файла они разделены между собой
apiVersion: v1
kind: Service
metadata:
  name: configserver
spec:
  selector:
    app: configserver
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080